language: php
php:
  - "5.5"
before_script: 
  - npm install -g grunt-cli
  - npm install
  # install apache2
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  # enable php-fpm
  - sudo cp ~/.phpenv/versions/5.5/etc/php-fpm.conf.default ~/.phpenv/versions/5.5/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/5.5/etc/php.ini
  - ~/.phpenv/versions/5.5/sbin/php-fpm
  # configure apache virtual hosts
  - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  - sudo service apache2 restart
script: npm run-script ci
branches:
  only:
    - master
env:
  - TYPES=unit
    JQUERIES=1.8.3
  - TYPES=unit
    JQUERIES=1.10.2
  - TYPES=unit
    JQUERIES=2.0.3
  - TYPES=unit
    JQUERIES=git
  - TYPES=integration
    SUITES=!navigation
    JQUERIES=1.8.3
  - TYPES=integration
    SUITES=!navigation
    JQUERIES=1.10.2
  - TYPES=integration
    SUITES=!navigation
    JQUERIES=2.0.3
  - TYPES=integration
    SUITES=!navigation
    JQUERIES=git
  - TYPES=integration
    SUITES=navigation
    JQUERIES=1.8.3
  - TYPES=integration
    SUITES=navigation
    JQUERIES=1.10.2
  - TYPES=integration
    SUITES=navigation
    JQUERIES=2.0.3
  - TYPES=integration
    SUITES=navigation
    JQUERIES=git

notifications:
  irc:
    channels:
      - "chat.freenode.net#jqueryui-dev"
